### ISSUE TITLE
Proper folder structure

### ISSUE THREAD

**Issue by k0msenapati** [SiddharthBahuguna/Diabetes-Prediction-Using-Machine-Learning#2]
The proper folder structure is required
Proposed folder structure
![image](https://github.com/SiddharthBahuguna/Diabetes-Prediction-Using-Machine-Learning/assets/92045934/84f9e75b-710d-4b4b-aded-17d68f6dcb75)

**Comment by SiddharthBahuguna** [comment]
You can add it.

**Comment by k0msenapati** [comment]
Ok assign me

**Comment by SiddharthBahuguna** [comment]
Please tell which label to be added here.

**Comment by kom-senapati** [comment]
Medium, vsoc
