### ISSUE TITLE
Video Demonstration

### ISSUE THREAD

**Issue by k0msenapati** [SiddharthBahuguna/Diabetes-Prediction-Using-Machine-Learning#31]
#### **Objective**
Create a comprehensive video tutorial explaining how to:
1. Set up and use Python virtual environments for our app.
2. Utilize various tools and frameworks including:
    - Flask app
    - Streamlit app
    - Gradio app
    - Tkinter GUI apps
    - Custom Tkinter (ctk) GUI apps
3. Run Jupyter notebooks using VS Code.
4. Use FastAPI swagger UI for API testing.

**Comment by k0msenapati** [comment]
Here is the video, I am not able to upload it to github so you can take necessary actions.

Link - https://www.dropbox.com/scl/fi/0hzpegrryti8kt9cfh5nu/Video-Demonstration.mp4?rlkey=jdhznsiuf2hlebrose42onep1&st=m056xdt8&dl=0

**Comment by SiddharthBahuguna** [comment]
Just upload the shareable link with the title
