### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by k0msenapati** [SiddharthBahuguna/Diabetes-Prediction-Using-Machine-Learning#4]
Creating a gui.py file under gui folder and removing the code present in readme file.

**Comment by SiddharthBahuguna** [comment]
But it is created in readme for better understanding.

**Comment by k0msenapati** [comment]
But readme can be edited and instructions can be added how to run, readme should not contain code I guess

**Comment by SiddharthBahuguna** [comment]
Ok.But please add instructions for better understanding.

**Comment by k0msenapati** [comment]
Solved in #6
